keys:
  - &ikostov2 age16dxn4nevrxhc8etm63a8juqssgjj09p6tw6e534nc6u892q2mg2s2mzsh9

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ikostov2
