# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ ./bluetooth ./boot ./cups ./displayManager ./filesystem ./firmware ./networking ./nvidia ./opengl ./pipewire ./security ./systemd ./xserver ];
}
