when:
  # branch: master
  event: [push]

steps:
  - name: deadnix
    image: nixpkgs/nix:latest
    commands:
      - nix run github:astro/deadnix --extra-experimental-features "nix-command flakes"

  - name: statix
    image: nixpkgs/nix:latest
    commands:
      - rm -rf ./archive
      - echo "Directory structure"
      - ls -l
      - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs --flake
      - nix-channel --update
      - nix-shell -p cachix --run "cachix use statix"
      - nix shell github:nerdypepper/statix -c statix check .
