when:
  # branch: master
  event: [push]

steps:
  - name: cachix
    image: nixpkgs/nix:latest
    commands:
      - nix --extra-experimental-features "nix-command flakes" shell nixpkgs#cachix -c cachix use iliyankostov9-nixos-config --authToken "${CACHIX_AUTH_TOKEN}"
      - nix flake check -L
