---
steps:
  - name: checkout
    image: alpine/git
    when:
      branch:
        - master
      event:
        - pull_request
      status: success
    commands:
      - echo "Checking out the repository"
      - git clone https://codeberg.org/iliyan-kostov/nixos-config
      - git fetch --depth 0
      - mkdir -p /artifacts
      - cp -r . /artifacts/nixos-config
      - echo "Repository saved to artifact directory"

  - name: scanning
    image: python:3.11
    when:
      branch:
        - master
      event:
        - pull_request
      status: success
    environment:
      # SONAR_TOKEN: $$SONAR_TOKEN
      GITGUARDIAN_API_KEY: $$GITGUARDIAN_API_KEY
    commands:
      - echo "Downloading repo artifact"
      - cp -r /artifacts/nixos-config .
      - echo "Running GitGuardian scan"
      - pip install ggshield
      - ggshield scan repo .
