steps:
  - name: scanning
    image: python:3.11.11 
    when:
      branch: feat/codeberg-webhook-trigger
      # event: pull_request
      event: push
      # status: success
    commands:
      - echo "test"
      - echo "Running GitGuardian scan"
      - python -m pip install --upgrade pip
      - pip install ggshield
      - ggshield scan repo .
