when:
  branch: master
  event: [pull_request]

steps:
  - name: scanning
    image: python:3.11.11
    commands:
      - echo $GITGUARDIAN_API_KEY
      - echo "Running GitGuardian scan"
      - python -m pip install --upgrade pip
      - pip install ggshield
      - ggshield secret scan repo .

    GITGUARDIAN_API_KEY:
      from_secret: GITGUARDIAN_API_KEY
