when:
  branch: master
  event: [pull_request]

steps:
  - name: scanning
    image: python:3.11.11
    commands:
      - python -m pip install --upgrade pip
      - pip install ggshield
      - ggshield secret scan repo .

    secrets: [GITGUARDIAN_API_KEY]
