# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      # (modulesPath + "/installer/scan/not-detected.nix")
      ./blueman.nix
      ./boot.nix
      ./bluetooth.nix
      ./filesystem.nix
      ./networking.nix
      ./nvidia.nix
      ./opengl.nix
      ./systemd.nix
      ./hardware.nix
      ./networking.nix
      ./security.nix
      ./services.nix
      ./systemPackages.nix
      ./xserver.nix
    ];

}
