name: Flake ❄️ Tests

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake ❄️ Checker ✅
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          sparse-checkout: |
            flake.nix
            flake.lock
          sparse-checkout-cone-mode: false

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25

      - uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1

  lock-updater:
    needs: flake-checker
    permissions:
      contents: write
      pull-requests: write

    name: Flake ❄️ Lock 🔒️ Updater ✨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          sparse-checkout: |
            flake.nix
            flake.lock
          sparse-checkout-cone-mode: false

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25

      - uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
