name: Nix ❄️ Static Analysis 🔍️

on:
  push:
    branches:
      - "!master"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deadnix:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    name: Dead Nix Analysis
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: astro/deadnix-action@main

  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Remove dirs to be ignored during scanning
        run: |
          rm -rf ./archive
          echo "Directory structure"
          ls -l

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: statix
      - uses: jocelynthode/statix-action@master

  vulnix:
    name: Run Vulnix for finding package CVEs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install nix action
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: iliyankostov9-nixos-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Vulnix for finding package CVEs
        run: |
          DRV=$(nix eval --raw .#nixosConfigurations.Lenovo-Legion-16ahp9.config.system.build.toplevel.drvPath)
          nix run nixpkgs#vulnix -- "$DRV"
