name: ❄️ Nix test ❄️

on:
  workflow_dispatch:

  # pull_request:
  #   branches:
  #     - none

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nix action
        uses: cachix/install-nix-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix build
        run: nix build

      - name: Nix install statix
        run: nix run git+https://git.peppe.rs/languages/statix -- --help

      - name: Nix flake check
        run: nix flake check

      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Run tests
        uses: cachix/install-nix-action@v29
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - name: Run statix
        run: statix check
