name: Nix ❄️ Static Analysis 🔍️

on: [push]
  # pull_request:
  #   branches:
  #     - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deadnix:
    strategy:
      matrix:
        os:
          # - macos-13 # x86_64-darwin
          # - macos-latest # aarch64-darwin
          - ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    name: Dead Nix Analysis
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: astro/deadnix-action@v1

  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove dirs to be ignored during scanning
        run: |
          rm -rf ./archive
          echo "Directory structure"
          ls -l

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
