name: ❄️ Nix test ❄️

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nix action
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: System tests
        run: nix build tests/system/default.nix

      - name: User tests
        run: nix build tests/user/default.nix

      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Run tests
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
