name: Statix

on:
  pull_request:
    branches:
      - master

jobs:
  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
