name: Statix

on:
  pull_request:
    branches:
      - master

jobs:
  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove dirs to be ignored during scanning
        run: |
          rm -rf ./archive
          echo "Directory structure"
          ls -l

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
